name: ptm
channels:
  - conda-forge
dependencies:
  # Required for full project functionality (dont remove)
  - pytest
  # Examples (remove and add as needed)
  - adios_db
  - aiohttp
  - appdirs
  - fastparquet
  # - geojson_pydantic
  - jupyter
  - jupyterlab
  - kerchunk
  - xarray
  - numpy
  - opendrift
  - scipy
  - dask
  - netcdf4
  - pandas
  - pip
  - pydantic
  - requests
  - matplotlib
  - zarr
