name: test_env_particle-tracking-manager
channels:
  - conda-forge
dependencies:
  - python=3.10
  ############## These will have to be adjusted to your specific project
  # - adios_db
  - aiohttp
  - numpy
  - cartopy
  - gdal
  - libgdal
    #- opendrift
  - scipy
  - xarray
  # - xroms
  ##############
  - codecov
  - pytest-cov
  - coverage
  - pip
  - pytest
  - pip:
    - git+https://github.com/OpenDrift/opendrift
    - git+https://github.com/fsspec/kerchunk
    # - xroms  # can't be found on conda-forge for CI, but don't need since in runslow tests?
